web:
  build: .
  ports:
    - "80:80"
  links:
    - kibana
    - elastic
kibana:
  image: kibana
  restart: always
  links:
    - elastic
  environment:
    - ELASTICSEARCH_URL=http://elastic:9200
  ports:
    - "5601:5601"
elastic:
  image: elasticsearch
  restart: always
  volumes:
    - /home/hans/ElasticSearch:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
